 language: cpp

 matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libxml2-dev libcppunit-dev libopencv-dev libjsoncpp-dev gfortran

 before_script:
   - cd ~/
   - git clone https://github.com/jhu-cisst/cisstNetlib
   - mkdir -p ~/cisstNetlib-build
   - mkdir -p ~/cisstNetlib-install
   - cd ~/cisstNetlib-build
   - cmake ~/cisstNetlib -DCMAKE_INSTALL_PREFIX=~/cisstNetlib-install
   - make install
   - mkdir -p ~/cisst-build
   - cd ~/cisst-build
   - cmake -C ~/build/jhu-cisst/cisst/.travis.cache.cmake ~/build/jhu-cisst/cisst

 script:
   - make
   - cd bin
   - ls -lR
   - ./cisstCommonTests -r
   - ./cisstVectorTests -r
   - ./cisstOSAbstractionTests -r
   - ./cisstNumericalTests -r

 notifications:
   email:
     - anton.deguet@jhu.edu
   on_success: change
   on_failure: always
