name: Windows 2016

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Download cisstNetlib
      run: |
        cmake -E make_directory ${{github.workspace}}/cisstNetlib-build
        git clone https://github.com/jhu-cisst/cisstNetlib ${{github.workspace}}/cisstNetlib-source

    - name: Build cisstNetlib
      working-directory: ${{github.workspace}}/cisstNetlib-build
      run: |
        cmake ${{github.workspace}}/cisstNetlib-source -A x64
        cmake --build . --config Release
        cmake --build . --target install

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -A x64 -DCMAKE_BUILD_TYPE=Release -C ${{github.workspace}}/.github/workflows/cmake-windows-cache.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        dir
        ./cisstvars.bat Release
        cmake --build . --config Release
        dir

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        dir bin/Release
        ./cisstvars.bat Release
        bin/Release/cisstCommonTests -r
        bin/cisstVectorTests -r
        cisstNumericalTests -r
        cisstOSAbstractionTests -r
        cisstParameterTypesTests -r
